name = "PlutoNotesGJGB.jl"
uuid = "e67aa1c4-e108-4233-888b-b76f089eefb8"
repo = "https://github.com/TavoJGB/PlutoNotesGJGB.jl"
description = "My structs and functions for Pluto notes."

[packages]
41ebad20-1491-4b27-9223-af85960c7184 = { name = "PlutoNotesGJGB", path = "P/PlutoNotesGJGB" }
